services:
  - type: web
    name: btc-trading-bot-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: starter
    autoDeploy: true
